// export const BASE_DEV_URL = "http://10.0.2.2:8800/api"
// export const BASE_DEV_URL = "https://clockwize-backend-production.up.railway.app/api"
export const SIGNUP_URL = "/auth/register"
export const LOGIN_URL = "/auth/login"
export const UPDATE_USER_PASSWORD = "/auth/updatePassword"
export const UPDATE_USER = "/auth/update"
export const UPLOAD_SINGLE_IMAGE = "/upload/"
"/album/"